---

- name: Create s3 bucket
  s3_bucket: 
    name: cr-coffee-time-prod

- name: Enable s3 website hosting
  s3_website:
    name: cr-coffee-time-prod
    state: present

# TODO: idempotent
- name: put index.html
  s3:
    bucket: cr-coffee-time-prod
    object: index.html
    src: "{{playbook_dir}}/roles/s3/files/index.html"
    mode: put
    permission: public-read