---

- name: Create s3 bucket
  s3_bucket: 
    name: "{{ s3_bucket_name }}"

- name: Enable s3 website hosting
  s3_website:
    name: "{{ s3_bucket_name }}"
    state: present

# TODO: idempotent
- name: put index.html
  s3:
    bucket: "{{ s3_bucket_name }}"
    object: index.html
    src: "{{playbook_dir}}/roles/s3/files/index.html"
    mode: put
    permission: public-read