---

- name: Create a dynamodb table
  dynamodb_table:
    name: "{{ dynamodb_table_name }}"
    region: "{{ aws_region }}"
    hash_key_name: id
    hash_key_type: STRING
    read_capacity: 2
    write_capacity: 2